services:
  postgres-db:
    image: postgres:15-alpine
    container_name: sensor_db
    environment:
      POSTGRES_USER: user_mecatronic
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: industrial_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sensor-api:
    build: .
    container_name: sensor_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      DB_URL: "postgres://user_mecatronic:password123@postgres-db:5432/industrial_monitor?sslmode=disable"

# ESTO ES LO QUE FALTABA:
volumes:
  postgres_data: